### ISSUE TITLE
Altered character names

### ISSUE THREAD

**Issue by HououinKyouma01** [Krokodyl/koi-wa-balance#2]
Hi. What was the reason of altering character names? 
Like seriously. Are you former 4kids employer or something?
Like Koyomi to Robin, Isuzu to Holly, Moe to Autumn etc. This is just nothing but pointless overlocalization that should not be a thing for few decades already. Especially that you have explained many other thing in readme file, so you could explain the meaning behind the names here too if it was so important. 
I just wanted to express my opinion, because it gets jarring when I see something like Autumn Cute instead Akiba Moe (which, by the way, completely changed what her name and surname showed anyway and moe =/= cute) or Robin Rustic instead Tokino Koyomi.  Yes, I know Japanese, so I often also look at the translations and wonder what went wrong and why. 
Don't get me wrong, this is not an attack towards you. Simply my 3 cents on what I see.

**Comment by Krokodyl** [comment]
> Hi. What was the reason of altering character names? 

Honestly, I don't remember. Feel free to make the changes you see fit and create a pull request.
Cheers.
